DROP TABLE IF EXISTS ipl_matches_denormalized;
CREATE TABLE ipl_matches_denormalized (
    id SERIAL PRIMARY KEY,
    city TEXT,
    dates DATE[],
    event_name TEXT,
    match_number INTEGER,
    gender TEXT,
    match_type TEXT,
    season TEXT,
    venue TEXT,
    team_a TEXT,
    team_b TEXT,
    toss_winner TEXT,
    toss_decision TEXT,
    outcome_winner TEXT,
    outcome_by_wickets INTEGER,
    outcome_by_runs INTEGER,
    player_of_match TEXT[],
    umpire_1 TEXT,
    umpire_2 TEXT,
    tv_umpire TEXT,
    match_referee TEXT,
    innings_val INTEGER,
    batting_team TEXT,
    over_num INTEGER,
    ball_num INTEGER,
    batter TEXT,
    bowler TEXT,
    non_striker TEXT,
    runs_batter INTEGER,
    runs_extras INTEGER,
    runs_total INTEGER,
    extra_wides INTEGER,
    extra_legbyes INTEGER,
    extra_noballs INTEGER,
    wicket_player_out TEXT,
    wicket_kind TEXT,
    wicket_fielders TEXT[],
    review_by TEXT,
    review_umpire TEXT,
    review_decision TEXT,
    review_type TEXT,
    impact_player_in TEXT,
    impact_player_out TEXT
)